const questions = [
  { id: 1, text: "I often get lost in my own thoughts and ideas.", reverse: false },
  { id: 2, text: "I enjoy daydreaming about possibilities that don't yet exist.", reverse: false },
  { id: 3, text: "I find myself inventing stories or scenarios in my head.", reverse: false },
  { id: 4, text: "I can easily picture things that aren't in front of me.", reverse: false },
  { id: 5, text: "My mind wanders into imaginative territory even during routine tasks.", reverse: false },
  { id: 6, text: "I enjoy discussing abstract or theoretical ideas.", reverse: false },
  { id: 7, text: "I like digging into a subject just to understand it better, even if it has no practical use.", reverse: false },
  { id: 8, text: "I ask 'why' or 'how' more than most people around me.", reverse: false },
  { id: 9, text: "I'm drawn to books, articles, or conversations that challenge how I think.", reverse: false },
  { id: 10, text: "I enjoy debating ideas even when I don't have a strong stake in the outcome.", reverse: false },
  { id: 11, text: "I'm moved by art, music, or poetry.", reverse: false },
  { id: 12, text: "I notice small details of beauty in everyday surroundings.", reverse: false },
  { id: 13, text: "I can spend a long time absorbed in a piece of music, writing, or visual art.", reverse: false },
  { id: 14, text: "Certain songs, paintings, or scenes affect my mood in a strong way.", reverse: false },
  { id: 15, text: "I actively seek out artistic or creative experiences (galleries, concerts, films, literature).", reverse: false },
  { id: 16, text: "I like trying activities I've never done before.", reverse: false },
  { id: 17, text: "I'm drawn to unfamiliar places, foods, or cultures.", reverse: false },
  { id: 18, text: "I get excited by the idea of an unplanned trip or spontaneous experience.", reverse: false },
  { id: 19, text: "I'd rather explore something new than stick with what I know works.", reverse: false },
  { id: 20, text: "I look forward to situations that push me outside my comfort zone.", reverse: false },
  { id: 21, text: "I prefer familiar ways of doing things over new approaches.", reverse: true },
  { id: 22, text: "Unusual people or ideas make me uneasy.", reverse: true },
  { id: 23, text: "I feel most comfortable when everyone follows the same accepted norms.", reverse: true },
  { id: 24, text: "I tend to dismiss ideas that sound too strange or unconventional at first.", reverse: true },
  { id: 25, text: "I prefer clear rules and traditional methods over experimental ones.", reverse: true },
  { id: 26, text: "I like having a predictable daily routine.", reverse: true },
  { id: 27, text: "I get restless if my schedule stays the same for too long.", reverse: false },
  { id: 28, text: "I'd rather revisit a place or activity I already know than try something new.", reverse: true },
  { id: 29, text: "I actively look for ways to mix up my regular routine.", reverse: false },
  { id: 30, text: "Sticking to a fixed plan feels more comfortable to me than improvising.", reverse: true }
];
